
#ifndef CONSTANTS_H
#define CONSTANTS_H

#define LOW_AXIAL_RESOLUTION 100
#define LOW_ANGULAR_RESOLUTION 20 
#define HIGH_AXIAL_RESOLUTION 300
#define HIGH_ANGULAR_RESOLUTION 60 
#define MAX_SUBCANE_COUNT 100
#define MAX_FILENAME_LENGTH 200

#define LOW_RESOLUTION 1
#define HIGH_RESOLUTION 2

#define ALL_SUBCANES -1
#define NO_SUBCANES -2

#define TWIST_TRANSFORM 1
#define STRETCH_TRANSFORM 2
#define MOVE_TRANSFORM 3
#define SQUAREOFF_TRANSFORM 4

#define UNASSIGNED_CANETYPE 0
#define TWIST_CANETYPE 1
#define STRETCH_CANETYPE 2
#define BUNDLE_CANETYPE 3
#define SQUAREOFF_CANETYPE 4
#define BASE_CIRCLE_CANETYPE 5

#define MAX_TRANSFORMS 20

#define MAX_NUM_CANES 100

#define LOOK_MODE 1
#define TWIST_MODE 2
#define STRETCH_MODE 3
#define BUNDLE_MODE 4
#define SQUAREOFF_MODE 5

#define PI 3.14159265358979323846f

#define MAX(a, b) (((a) > (b)) ? (a) : (b))
#define MIN(a, b) (((a) < (b)) ? (a) : (b))

#endif


