
#ifndef CONSTANTS_H
#define CONTANTS_H

#define LOW_AXIAL_RESOLUTION 100
#define LOW_ANGULAR_RESOLUTION 20 
#define HIGH_AXIAL_RESOLUTION 300
#define HIGH_ANGULAR_RESOLUTION 60 
#define MAX_SUBCANE_COUNT 100
#define MAX_FILENAME_LENGTH 200

#define LOW_RESOLUTION 1
#define HIGH_RESOLUTION 2

#define STRETCH 1
#define TWIST 2
#define WRAP 3
#define BUNDLE 4

#define ALL_SUBCANES -1
#define NO_SUBCANES -2

#define PI 3.14159265358979323846f

#endif


