
#ifndef PULLTEMPLATE_H
#define PULLTEMPLATE_H

#include <vector>
#include "primitives.h"
#include "subpulltemplate.h"
#include "constants.h"

// Pull template types
#define CIRCLE_BASE_PULL_TEMPLATE 1
#define SQUARE_BASE_PULL_TEMPLATE 2
#define AMORPHOUS_BASE_PULL_TEMPLATE 3
#define CASED_CIRCLE_PULL_TEMPLATE 4
#define CASED_SQUARE_PULL_TEMPLATE 5
#define HORIZONTAL_LINE_CIRCLE_PULL_TEMPLATE 6
#define HORIZONTAL_LINE_SQUARE_PULL_TEMPLATE 7
#define TRIPOD_PULL_TEMPLATE 8
#define CROSS_PULL_TEMPLATE 9
#define SQUARE_OF_CIRCLES_PULL_TEMPLATE 10
#define SQUARE_OF_SQUARES_PULL_TEMPLATE 11
#define SURROUNDING_CIRCLE_PULL_TEMPLATE 12
#define SURROUNDING_SQUARE_PULL_TEMPLATE 13
#define CUSTOM_CIRCLE_PULL_TEMPLATE 100
#define CUSTOM_SQUARE_PULL_TEMPLATE 101

#define FIRST_PULL_TEMPLATE CASED_CIRCLE_PULL_TEMPLATE
#define LAST_PULL_TEMPLATE SURROUNDING_SQUARE_PULL_TEMPLATE 

// Custimization modes

#define MOVE_MODE 1
#define SCALE_MODE 2


#endif

